### ISSUE TITLE
Cannot currently handle multiple subscribers in same application

### ISSUE THREAD

**Issue by WallStProg** [fquinner/OpenMAMA-zmq#15]
Getting the error above when running a simple test pgm that creates multiple subscribers.

The full msg is:

    2017-06-02 14:58:43: zmqBridgeMamaTransportImpl_dispatchThread(): Cannot currently handle multiple subscribers in same application

Curious if this is on the "roadmap", or if you have any hints/tips as to the issue.  I'm happy to roll up my sleeves and take a whack at it...

Thanks!

**Comment by fquinner** [comment]
There's a TODO if that counts :)

https://github.com/fquinner/OpenMAMA-zmq/blob/master/src/transport.c#L1129

I left that non implemented while I was experimenting with different queuing and memory pool approaches to save effort and forgot to revisit. Basically it needs to do what the qpid bridge does here.

You're welcome to have a crack thanks! Otherwise I'll get it done when I get a chance. If I start work on it, I'll update this ticket so we don't duplicate effort.

**Comment by WallStProg** [comment]
So I've taken a look at qpid bridge, and in both it and zmq I see following comment:

    /* Within this loop, queue callbacks release the pool messages */

I'm curious what this means, and whether the memory mgmt requirements for the bridges are documented somewhere.

With other MW (i.e., TibRV), the incoming message is owned by the MW, is created once for all callbacks, and deleted automatically following return from last callback.  If an application wants to retain a msg, it needs to either copy it or explicitly take ownership of it.

It looks the Mama approach is different?  Or am I reading this wrong?

Thanks!

**Comment by fquinner** [comment]
Yeah memory management is always middleware dependent. Qpid and zmq have similar memory management limitations - the middleware gets you as far as a single message buffer for a topic, then you have to add your own stuff for asynchronous processing and subscription matching (I.e. mama queues and hash tables). So a memory node is taken from the pool, payload and supporting data (I.e subscription for callback) are populated, then its enqueued on the application provided queue (when the subscription was created). The callback then returns the node to the pool for reuse after the callback. This is all optional - its possible for the dispatch thread to just call the callback directly and cut out the copies and locks but obviously that wont scale very well if your application has lots of cores and mama queues to run across.

**Comment by WallStProg** [comment]
Thanks -- that all makes sense (I think).

So it would seem that one way to enable multiple subscriptions is simply to remove the `if (subInc != (subCount - 1)` test and handle each iteration identically.  

It would be nice if there were an optimization for when `subCount == 1`, but based on your description that doesn't appear to be the case.

Does that make sense?

**Comment by fquinner** [comment]
Yeah that was copied from qpid originally where it actually did benefit from a slight optimization because it cut out an additional proton message constructor but in this case you're right there doesn't appear to be any advantage to treating the last message differently where multiple subscriptions are present.

**Comment by WallStProg** [comment]
Attached is a patch for this -- please let me know what you think.


[diff.txt](https://github.com/fquinner/OpenMAMA-zmq/files/1064754/diff.txt)

**Comment by fquinner** [comment]
Thanks Bill looks good - changed a little to remove mixed declarations but otherwise it's untouched. Just submitted it there: b389bd15b5a21db8f97615a47200cadcb4b18ab3

**Comment by WallStProg** [comment]
Great.  The declaration thing -- curious where that convention comes from.  AFAIK it has zero benefit in terms of performance, but is frowned upon by some (incl. me) who believe it is less readable.  (Not to start a holy war, just asking ;-)

**Comment by fquinner** [comment]
Yeah it's to prevent build issues on older versions of MSVC - personally I prefer to keep declarations near their first use to make it clear that they're not used before that point but this is the OpenMAMA way, primarily because of winblows.

**Comment by WallStProg** [comment]
Frank -- can you email directly about a possible issue with the patch (wallstprog at gmail).  thx
